### ISSUE TITLE
Some extensions ignore HUB_WORKDIR variable

### ISSUE THREAD

**Issue by TheRealSpaceShip** [agilestacks/hub-extensions#113]
This issue is occurred when a user define `HUB_WORKDIR` environment variable and runs `hubctl` commands outside of `hub.yaml` file.

Steps:

1. Create a directory somewhere and place a simple [`hub.yaml`](https://hubctl.io/tutorials/010-hubctl-stack-init/#about) there.
2. Go outside of this directory and create a `HUB_WORKDIR` variable where the value is the absolute path to the created directory
3. Run `hubctl stack init -f "$HUB_WORKDIR/hub.yaml"`
4. Run `hubctl stack configure`

Actual result: 

```text
Cannot find hubctl files! Please run "hubctl stack init"

Example:
  hubctl stack init -f hub.yaml
or
  hubctl stack init -f https://raw.githubusercontent.com/epam/hub-google-stacks/main/gke-empty-cluster/hub.yaml
```

Expected result: a run of `hubctl stack configure` should be successful.

**Comment by akranga** [comment]
Introducing some unit-testing for `hub-stack-deploy` as part of #114 bumped into very similar behaviour there as well... Will rebase #114 with current. Will give it a try
