### ISSUE TITLE
Bats-core as unit test framework

### ISSUE THREAD

**Issue by TheRealSpaceShip** [agilestacks/hub-extensions#13]
To provide the stability of extensions and ensure that new changes or bug fixes will not break anything, we need to cover the current implementation with unit tests. This will potentially help us migrate from bash to some programming language in the future. One possible solution is to use https://github.com/bats-core/bats-core. Bats is a [TAP](https://testanything.org/)-compliant testing framework for Bash.

Subtasks are next:

- [x] review bats-core
- [x] implement some basic unit tests for couple of extensions
- [x] develop a process of running unit tests and reporting results
- cover extensions with unit test (long term task)
- hub extensions packaging and delivery (to exclude test scripts and libs from extensions)

**Comment by akranga** [comment]
Need to understand driver for BATS. Should it be a GH Actions? Or only from local command? or anything else?

**Comment by TheRealSpaceShip** [comment]
That's why `develop a process` is a third task :). To give an answer to your question first need to try BATS. Ideally, it's to run it locally as git hook (commit or push) and then run as part of CI (GH Actions)

**Comment by TheRealSpaceShip** [comment]
To enable git hooks for extensions just run `npm install` in root of the repo
