### ISSUE TITLE
Merge `gcp-extensions` to `master`

### ISSUE THREAD

**Issue by akranga** [agilestacks/hub-extensions#20]
Once `hooks` has been implemented (see: [hub/13](https://github.com/agilestacks/hub/issues/13) then it should be possible to merge hub-extension to master

- [x] Merge to master branch
- [x] Update toolbox (cloud shell and gcp tool box) GH actions and Dockerfile to rely to new branch

**Comment by oginskis** [comment]
Merged `gcp-extensions` into `master`. Bumped `stable` tag to point to the latest commit in the `master` branch. Cloud shell and gcp toolbox check out the extensions from `stable` tag by default
