### ISSUE TITLE
Stack deployment issues on WSL 2

### ISSUE THREAD

**Issue by oginskis** [agilestacks/hub-extensions#68]
A user started using `hubctl` tooling on his Windows Subsystem for the Linux Ubuntu environment and faced the following issues:
- [x] `hubctl` installation using instructions from https://hubctl.io/install/ (the `curl` based) failed with:
```
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
tar: Refusing to read archive contents from terminal (missing -f option?)
tar: Error is not recoverable: exiting now
``` 
`wget` based installation worked

- [x] `hubctl extensions install` failed with:
```
hubctl extensions install
Cloning into '/home/xxx/.hub'...
remote: Enumerating objects: 3346, done.
remote: Counting objects: 100% (1153/1153), done.
remote: Compressing objects: 100% (430/430), done.
remote: Total 3346 (delta 760), reused 1093 (delta 714), pack-reused 2193
Receiving objects: 100% (3346/3346), 778.12 KiB | 1.57 MiB/s, done.
Resolving deltas: 100% (2090/2090), done.
/bin/sh: 0: Illegal option -
2023/05/03 10:12:53 WARN: Unable to run post-install hook in /home/xxx/.hub: exit status 2
2023/05/03 10:12:53 Hub CTL extensions installed into /home/xxx/.hub
```
after that user tried to run `hubctl stack ...` commands against the template, but also got the `Illegal option -` error. That is probably because the extensions were not installed properly in the `hubctl extensions install` step

We need to validate that a user can install and start using our automation on the clean WSL environment.

**Comment by TheRealSpaceShip** [comment]
A user reported that the issue was in Windows line-endings for shell scripts which cause by git configuration `core.autocrlf`. 
To fix it reconfigure `git` to checkout code as-is and commit Unix-style: `git config --global core.autocrlf input`

**Comment by akranga** [comment]
Please advise if this is still actual?

**Comment by oginskis** [comment]
I believe, it's not.
@akranga Can we ask one of the new team members to update the documentation site with information about line endings for WSL users?

**Comment by akranga** [comment]
Sure, yet @TheRealSpaceShip would you advise what exactly needs to be updated? Thanks!

**Comment by TheRealSpaceShip** [comment]
@akranga We need to create a complete guide on how to set up Windows machine from scratch to use `hubctl`. 
This includes:
* Install WSL
* Base setup of WSL (enable `systemd`, configure git to handle line endings properly)
* Install required tools (bash, curl, jq, yq)
* Install optional tools like docker, helm, kubectl, etc.
* Install development apps like VS Code (but this is optional)

**Comment by akranga** [comment]
@TheRealSpaceShip agree on the guide. Little help is needed here. Anyone?

**Comment by TheRealSpaceShip** [comment]
I have created an issue in the hubctl.io repo. Close this one as done.
