### ISSUE TITLE
Syncronizing hub extensions: mkdir: can't create directory: Permission denied

### ISSUE THREAD

**Issue by arkadijs** [agilestacks/hub-extensions#7]
* Syncronizing hub extensions from: /home/arkadi/Work/agilestacks/hub-extensions
    mkdir: can't create directory '/home/arkadi/Work/agilestacks/': Permission denied
    command terminated with exit code 1

    Stand by while gracefully terminating toolbox-af906700
    * Cleaning toolbox-af906700: Done
    Aborted!
    ---

**Comment by akranga** [comment]
Need some steps to reproduce!

**Comment by arkadijs** [comment]
I run `hub stack deploy` with `HUB_EXTENSIONS=/home/arkadi/Work/agilestacks/hub-extensions` set in OS environment and the above is what I got.
