### ISSUE TITLE
`hubctl stack init` support for AWS

### ISSUE THREAD

**Issue by oginskis** [agilestacks/hub-extensions#86]
It's proposed to add an AWS-specific `hubctl stack init` extension that improves the user experience.

When a stack `requires: aws` and a user hits `hubctl stack init` the following must happen:

- [x] Check if a user has at least one AWS profile configured. Use `aws configure list-profiles` command or similar. If no profiles are available fail and ask the user to run `aws configure` or `aws configure sso`
- [x] If profiles are available, list them and ask the user to choose one of the profiles, set the name of the profile to the `AWS_PROFILE` environment variable in the `.env` file. See https://github.com/epam/hub-extensions/blob/develop/gcp/init#L143 as an example.
- [x] Ask the user to provide an AWS_REGION: try to get a default region of the user profile with `aws configure get region --profile <profile>` command, propose the user use the default region of the profile, but also allow to override it! Set discovered region to the AWS_REGION environment variable.

The `init` extension must be placed in this directory: https://github.com/epam/hub-extensions/tree/develop/aws
Example `init` extension for `GCP`: https://github.com/epam/hub-extensions/blob/develop/gcp/init

**Comment by oginskis** [comment]
@akranga Can @NellyHargeliya and @seseque take this?

**Comment by seseque** [comment]
@oginskis I would like to take this task

**Comment by akranga** [comment]
@seseque please feel free to assign it pro-actively

**Comment by akranga** [comment]
@seseque should we close this issue?
